spring:
  application:
    name: manga-bot
  messages:
    fallback-to-system-locale: false
  security:
    user:
      name: admin
      password: pass
  datasource:
    url: jdbc:postgresql://192.168.1.72:5432/tgBot
    username: postgres
    password: docker
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false


bot:
  admin: -1
  token: lel